### ISSUE TITLE
No matching distribution found for tensorflow==1.12.0 

### ISSUE THREAD

**Issue by uncojohnco** [SchoolofAI-Vancouver/NLP_Project_3#10]
Hi,

It looks like tensorflow is currently on compatible with `python<=v3.5`. 😦 
I had initially created  a conda env with python 3.6 and got the below error

```
Collecting tensorflow==1.12.0 (from -r requirements.txt (line 27))
  Could not find a version that satisfies the requirement tensorflow==1.12.0 (from -r requirements.txt (line 27)) (from versions: )
No matching distribution found for tensorflow==1.12.0 (from -r requirements.txt (line 27))
```

Creating a conda environment against python 3.5 resolved the issue...
``` python
conda create -n <ENVIRONMENT_NAME>  python=3.5 anaconda
```

https://github.com/SchoolofAI-Vancouver/NLP_Project_3/blob/12def12ac48039d92b5b85e17d4860909789c57d/requirements.txt#L27

**Comment by xinbinhuang** [comment]
@oikake The workshop is originally designed for Python 3.6, so there may be some compatible issues when working with different python version.

**Comment by xinbinhuang** [comment]
Update in README. 0bf3f929d4a89499ea20aa537a1a0859699cffba
