### ISSUE TITLE
python3.5 incompatibilities

### ISSUE THREAD

**Issue by uncojohnco** [SchoolofAI-Vancouver/NLP_Project_3#11]
Edit: I used Conda initially to setup my environment initially...

My environment is using python3.5, due tensorflow not compatible with >= python3.6(?) and is throwing a few version incompatibilities

## Doesn't support f-string feature 😦 
https://github.com/SchoolofAI-Vancouver/NLP_Project_3/blob/12def12ac48039d92b5b85e17d4860909789c57d/ml_model/download.py#L34
```
File "/Users/jayCee/PycharmProjects/school_of_ai/NLP_Project_3/ml_model/download.py", line 34
    print(f"Downloading and extracting {task}")

SyntaxError: invalid syntax
```

```python
# Use str.format method? 
print("Downloading and extracting {task}".format(**locals()))
```

## TypeError: join() argument must be str or bytes, not 'PosixPath'
https://github.com/SchoolofAI-Vancouver/NLP_Project_3/blob/12def12ac48039d92b5b85e17d4860909789c57d/ml_model/download.py#L20-L23

```python
# cast result of DIR_ROOT = get_root() into a str?
DIR_ROOT = str(get_root())
```

**Comment by xinbinhuang** [comment]
For f-string, Similar to issue #10. See 0bf3f929d4a89499ea20aa537a1a0859699cffba

Can you print the output for `get_root()` and `type(get_root())`?

**Comment by uncojohnco** [comment]
This can be closed as i suspect my venv seemed polluted 🤷‍♂️  following the instructions in the readme using python 3.6 and venv and pip works as expected 👍
